---
title: "Zotero werkcollege"
author:
  - name: Ronald Visser
    orcid: 0000-0001-6966-1729
    email: r.m.visser@saxion.nl
    affiliation: 
      - name: Saxion University of Applied Sciences
        city: Deventer
        country: Netherlands
  - name: Loes Opgenhaffen
    orcid: 0000-0001-8940-8878
    email: l.opgenhaffen@saxion.nl
    affiliation: 
      - name: Saxion University of Applied Sciences
        city: Deventer
        country: Netherlands
date: today
---

Deze website is een werkcollege gemaakt voor de opleiding [Archeologie](https://www.saxion.nl/opleidingen/voltijd/bachelor/archeologie) bij [Saxion](https://www.saxion.nl/). Het doel van deze les is leren werken met [Zotero](https://www.zotero.org/).

## Wat is Zotero?

Zotero is bibliografische software. Het wordt ook wel een referentiemanager genoemd. Tegenwoordig kun je er veel meer mee dan alleen het bijhouden van referenties, zoals het opslaan van notities en samenvattingen. Zotero is een onmisbaar middel om onderzoek te doen en helpt je om literatuuronderzoek en bronnenonderzoek systematisch bij te houden. Daarnaast kun je ook de databronnen hiermee beheren. Kortom, alle gegevens waar je naar moet kunnen verwijzen kun je hiermee opslaan en opvragen.

Video met korte uitleg over wat Zotero is:

<iframe id="kaltura_player" type="text/javascript"  src='https://api.frp2.ovp.kaltura.com/p/10345/embedPlaykitJs/uiconf_id/23456908?iframeembed=true&entry_id=0_yd4zxbuw&config[provider]={"widgetId":"0_kkc97bzq"}'  style="width: 720px;height: 405px;border: 0;" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" sandbox="allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" title="Kaltura Player"></iframe>

De onderstaande video laat Zotero in het gebruik zien, als je een idee wil krijgen van de mogelijkheden.

<iframe id="kaltura_player" type="text/javascript"  src='https://api.frp2.ovp.kaltura.com/p/10345/embedPlaykitJs/uiconf_id/23456908?iframeembed=true&entry_id=0_je76zm06&config[provider]={"widgetId":"0_ks9wr0zs"}'  style="width: 720px;height: 405px;border: 0;" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" sandbox="allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" title="Kaltura Player"></iframe>

